services:

  plex:
    image: jaymoulin/plex:1.41.0.8992
    expose:
      - 32400
      - 33400
    # Descomentar si NO usas network_mode: "host"
    # ports:
    #  - 32400:32400
    #  - 33400:33400
    environment:
      - TZ=America/Argentina/Buenos Aires
    volumes:
      - ${PLEX_STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${PLEX_MEDIA}:/media
      - ${PLEX_STORAGE}/tmp:/tmp
    restart: unless-stopped
    network_mode: "host" # Solo funciona en Linux
  sonarr:
    image: ghcr.io/hotio/sonarr
    ports:
    - 8089:8989
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: "Etc/UTC"
    volumes:
      - sonnar_config:/config
      - ./data:/data
volumes:
  sonarr_config:


  # transmission:
  #   image : jaymoulin/transmission:3.00-1.6.1
  #   command: transmission-daemon -f -g /config
  #   volumes:
  #     - ./transmission:/config
  #     - ${STORAGE}/torrents:/downloads
  #   ports:
  #     - 9091:9091
  #     - 51413:51413
  #     - 51413:51413/udp
  #   expose:
  #     - 9091
  #   restart: unless-stopped

  # flexget:
  #   image: wiserain/flexget:3.5
  #   volumes:
  #     - ./flexget:/config
  #     - ./flexget/custom-cont-init.d:/custom-cont-init.d
  #     - ${STORAGE}/torrents:/downloads
  #     - ${MEDIA}:/storage
  #   ports:
  #     - 5050:5050
  #   environment:
  #     - PUID=1001
  #     - PGID=1001
  #     - TORRENT_PLUGIN=transmission
  #     - FG_WEBUI_PASSWD=p3l4d0_N3RD # la puedes cambiar por la que quieras
  #   restart: unless-stopped
