services:

  plex:
    image: jaymoulin/plex:1.41.0.8992
    expose:
      - 32400
      - 33400
    environment:
      - TZ=America/Argentina/Buenos Aires
    volumes:
      - ${PLEX_STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${PLEX_MEDIA}:/media
      - ${PLEX_STORAGE}/tmp:/tmp
    restart: unless-stopped
    network_mode: "host" # Solo funciona en Linux
  sonarr:
    image: ghcr.io/hotio/sonarr
    ports:
    - 8089:8989
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: "Etc/UTC"
    volumes:
      - sonarr_config:/config
      - ./sonarr/data:/data
    networks:
      plex_network:
        ipv4_address: 10.0.2.2
  radarr:
    image: ghcr.io/hotio/radarr
    ports:
    - 8090:7878
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: 002
      TZ: "Etc/UTC"
    volumes:
      - radarr_config:/config
      - ./radarr/data:/data
      - /downloads:./movies
    networks:
      plex_network:
        ipv4_address: 10.0.2.4
  transmission:
    image : jaymoulin/transmission:3.00-1.6.1
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission/config:/config
      - ./transmission/torrents:/downloads
    ports:
    - 9091:9091
    - 51413:51413
    - 51413:51413/udp
    expose:
    - 9091
    restart: unless-stopped
    networks:
      plex_network:
        ipv4_address: 10.0.2.3
volumes:
  sonarr_config:
  radarr_config:
networks:
  plex_network:
    name: 'plex_network'
    ipam:
        config:
          - subnet: 10.0.2.0/24
