services:
 portainer:
  image: portainer/portainer-ce:2.21.0
  ports:
   - 8000:8000
   - 9443:9443
  restart: always
  volumes:
   - portainer_data:/data
   - /var/run/docker.sock:/var/run/docker.sock
volumes:
 portainer_data:

