services:
  pihole:
    image: pihole/pihole:2026.05.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: ${PORTAINER_PASSWORD}
    # Volumes store your data between container upgrades
    volumes:
       - pihole_data:/etc/pihole/
       - pihole_dnsmasq:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      dockerserver_network:
        ipv4_address: 10.0.1.2
  samba:
    image: dperson/samba # no hay tag con versiones, solo latest
    restart: always
    command: '-u "${SAMBA_USER};${SAMBA_PASSWORD}" -s "shared;/shared;yes;no;no;leandro;;leandro;" -s "plex;/plex;yes;no;no;leandro;;leandro;"' 
    stdin_open: true
    tty: true
    environment:
      - TZ=America/Argentina/Buenos Aires
    ports:
      - 139:139
      - 445:445
    volumes:
      - samba_data:/shared
      - /mnt/old_disk/media:/plex:rw
      - ./samba/smb.conf:/etc/samba/smb.conf:rw
    networks:
      dockerserver_network:
        ipv4_address: 10.0.1.5
  portainer:
    image: portainer/portainer-ce:2.39.2
    ports:
      - 9000:9000
      - 9443:9443
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      dockerserver_network:
        ipv4_address: 10.0.1.4
  kestra:
    image: kestra/kestra:latest
    ports:
    - 8085:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    command: ["server","local"]
    networks:
      dockerserver_network:
        ipv4_address: 10.0.1.8
  uptime_kuma:
    image: louislam/uptime-kuma:2.3.2
    ports: 
    - 3001:3001
    restart: always
    volumes:
      - uptime-kuma_data:/app/data
    networks:
      dockerserver_network:
        ipv4_address: 10.0.1.7
  alpine_ftp_server:
    image: delfer/alpine-ftp-server
    ports:
    - 21:21
    environment:
      - USERS=${FTP_USERS}
    restart: always
    volumes:
      - ./shared:/ftp
    networks:
      dockerserver_network:
        ipv4_address: 10.0.1.6
  flame:
    image: pawelmalak/flame:2.4.0
    volumes:
      - flame_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
    ports:
      - 80:5005
    secrets:
      - flame_password # optional but required for (1)
    restart: unless-stopped
    networks:
      dockerserver_network:
        ipv4_address: 10.0.1.9
  kopia:
    image: kopia/kopia:latest
    hostname: Hostname
    restart: unless-stopped
    ports:
        - 51515:51515
    # Setup the server that provides the web gui
    command:
        - server
        - start
        - --disable-csrf-token-checks
        - --insecure
        - --address=0.0.0.0:51515
        - --server-username=${KOPIA_SERVER_USERNAME}
        - --server-password=${KOPIA_SERVER_PWD}
    environment:
        # Set repository password
        KOPIA_PASSWORD: ${KOPIA_REPO_PWD}
        USER: ${KOPIA_REPO_USERNAME}
    networks:
      dockerserver_network:
        ipv4_address: 10.0.1.10
    volumes:
        # Mount local folders needed by kopia
        - kopia_config:/app/config
        - kopia_cache:/app/cache
        - kopia_logs:/app/logs
        # Mount local folders to snapshot
        - kopia_data:/data:ro
        # Mount repository location
        - kopia_repo:/repository
        # Mount path for browsing mounted snaphots
        - kopia_tmp:/tmp:shared
volumes:
  samba_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../data/samba/shared
  flame_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../data/flame_data
  pihole_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../data/pihole_data
  pihole_dnsmasq:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../data/pihole_dnsmasq
  portainer_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../data/portainer_data
  uptime-kuma_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ../data/uptime-kuma_data
  kopia_config:
  kopia_cache:
  kopia_logs:
  kopia_data:
  kopia_repo:
  kopia_tmp:
secrets:
  flame_password:
    file: ./secret/flame_password
networks:
  dockerserver_network:
      name: 'dockerserver_network'
      ipam:
          config:
            - subnet: 10.0.1.0/24
